export const FETCH_REPOS_SUCCESS = 'FETCH_REPOS_SUCCESS';
export const FETCH_DETAILS_SUCCESS = 'FETCH_DETAILS_SUCCESS';
export const FETCH_REPOS_REQUESTED = 'REPOS_FETCH_REQUESTED';
export const FETCH_DETAILS_REQUESTED = 'FETCH_DETAILS_REQUESTED';
export const FETCH_REPOS_FAILED = 'FETCH_REPOS_FAILED';
export const FETCH_DETAILS_FAILED = 'FETCH_DETAILS_FAILED';
